package com.example.lorna.ltodriverslicwrittenexamapp;

public class QuestionLibrary {

    private String mQuestions[] = {
            "Which place you should not overtake?",
            "Which of the following describes the picture:",
            "A person who drives while under influence of alcohol or drugs is punishable by law with:",
            "Which of the following describes the picture:",
            "If you are involved in an accident, you should inform the nearest police station:",
            "Which of the following describes the picture:",
            "The vehicle horn is used for:",
            "What is the meaning of yellow arrow traffic light?",
            "It is more dangerous to turn left than to turn right because:",
            "Broken yellow line on the road means:",
            "If you want to drive slower than other vehicles on a highway you should stay on the:",
            "You can overtake in a highway if it has two lanes with:",
            "A continuous parallel double yellow line on the road means:",
            "Which of the following describes the picture:",
            "Having a license means you can drive:",
            "You are not allowed to overtake at the foot bridge because:",
            "A driver is considered a Professional driver if:",
            "Which of the following describes the picture:",
            "The safest response even if you have rights on the road is:",
            "After overtaking, you want to safely go back to the lane where you where you came from, you should:",
            "Double broken yellow line in the road means:",
            "You can overtake in the right side of your vehicle if:",
            "What is the maximum speed of a vehicle entering a school zone?",
            "Obtaining a driver’s license is:",
            "If a vehicle in front of you has a high beam light which is blinding your vision, what should you do?",
            "What should you do before turning left or right?",
            "What should you bring before driving a vehicle?",
            "Which of the following describes the picture:",
            "A red flag or red light should be attached to any vehicle cargo that exceeds:",
            "What is the meaning of a circle, octagon or inverted triangle traffic sign with red border color?",
            "What is the meaning of green arrow traffic light?",
            "What should you do if the vehicle behind you wants to overtake your vehicle?",
            "What is the meaning of an arrow painted on the road?",
            "What is the meaning of blinking red traffic light?",
            "In an intersection with a STOP sign, you should:",
            "In a roundabout (rotunda), which has road rights?",
            "Which of the following describes the picture:",
            "When riding a motorcycle and you would like to turn right, you should signal with:",
            "What is the meaning of a triangle traffic sign with red border color?",
            "Which of the following describes the picture:",
            "What are white lines in the road for?",
            "A continuous single yellow line on the road means:",
            "The minimum age in the application for Non-Professional Driver’s License is:",
            "The vehicle is parked if:",
            "If the brake light of the vehicle in front of you lights up, you should:",
            "When parking uphill and parallel to the sidewalk, you should turn the wheel:",
            "You are not allowed to cross a lane with continuous yellow line on the road except if you are:",
            "What is the meaning of continuous yellow line in the road?",
            "While driving, you should look at your side and rear view mirror:",
            "What is the meaning of yellow traffic light?",
            "What is the meaning of blinking yellow traffic light?",
            "A driver should give a signal when turning left or right on the road intersection in no less than:",
            "Which of the following describes the picture:",
            "Before leaving the parking area, you should:",
            "Which of the following describes the picture:",
            "What is the meaning of blinking red traffic light?",
            "If you are caught due to a violation, how many days are given for you to settle your case and get your license back?",
            "Which of the following describes the picture:",
            "Which of the following describes the picture:",
            "Which of the following describes the picture:",
            "What should you do when an ambulance comes up behind you flashing red lights and/or sounding its siren?",
            "Which of the following describes the picture:",
            "When should a driver make a decision?",
            "Before changing lanes on a highway, you must give a signal for:",
            "Which of the following describes the picture:",
            "Which of the following describes the picture:",
            "What should a driver take action if his/her driver’s license was lost?",
            "Which of the following describes the picture:",
            "What is the meaning of green traffic light?",
            "In which place you are prohibited to park?",
            "According to the law, you are not allowed to drive fast, except when:",
            "Broken white line on the road means:",
            "What should you do to combat fatigue and sleepiness during long road trip?",
            "Not following road and traffic rules:",
            "Which of the following describes the picture:",
            "There are two incoming vehicles on both sides of the street of an intersection with no traffic light, which vehicle should give way?",
            "The safest speed of a vehicle is according to:",
            "Driving with a fake license is prohibited and punishable by:",
            "Which of the following describes the picture:",
            "The minimum age for the applicant of Professional Driver’s License is:",
            "Which of the following describes the picture:",
            "If the driver of a vehicle in front of you is giving a hand signal and is pointing his hand to the ground, he is:",
            "Driving without license is against the law and punishable with a fine of:",
            "If you are approaching a curve, what should you do?",
            "If the driver of a vehicle in front of you is giving a hand signal by pointing his left hand upwards, he will surely:",
            "While changing lanes, you should give signal, check your rear view mirror and:",
            "What should you prepare for a long trip?",
            "A Non-Professional driver’s license is suited for:",
            "The necessary distance in between you and a vehicle you are following should be:",
            "Which of the following describes the picture:",
            "Which of the following describes the picture:",
            "If you are going to drive slow on expressway, you should move on the:",
            "What is the meaning of green traffic light?",
            "Which of the following describes the picture:",
            "What is the meaning of a square or rectangle traffic sign with blue and white color?",
            "Which of the following describes the picture:",
            "Which of the following describes the picture:"
    };

    private String mChoices [][] = {
            {"All answers are correct", "At the foot of the bridge", "In an intersection"},
            {"Priority crossroads", "Sharp turn to the right", "Sharp turn to the left"},
            {"Fines and imprisonment", "Suspension of license", "All answers are correct"},
            {"Double turn to the left", "Double turn ahead", "Double turn to the right"},
            {"Immediately", "Within 72 hours", "Within 48 hours"},
            {"No blowing of horns", "No parking", "No U-turn"},
            {"Creating noise", "Making beautiful sounds", "Giving warning to avoid accident"},
            {"Giving signal for right or left direction", "Allowing vehicles to go left, right or straight", "The red arrow traffic light is about to light up"},
            {"Vehicles coming from left is faster", "You have to be aware and cautious from vehicles coming from left or right sides of the road", "The road has more lanes"},
            {"You are allowed to overtake on the right side", "You are allowed to overtake on the left side", "It is prohibited to overtake on the left or right side"},
            {"Right lane", "Left lane", "Middle lane"},
            {"Continuous yellow line", "Broken yellow line", "Continuous white line"},
            {"You are allowed to overtake on the right side", "It is dangerous to overtake", "You are allowed to overtake on the left side"},
            {"No entry for trucks", "No entry for bus", "No entry for car"},
            {"All types of vehicle", "Vehicles allowed indicated in your license", "Public utility vehicle only"},
            {"People are crossing", "You cannot see oncoming vehicles", "The bridge is narrow"},
            {"He/she is a driving expert", "He/she is paid or earns money while driving a private or public vehicle", "He/she can drive any vehicle"},
            {"Stop", "Give way", "No entry"},
            {"Don’t force your rights", "Force your rights", "Sound your horn"},
            {"Stop", "Use the rear view mirror to check the vehicle you have overtaken", "Look at the vehicle you have overtaken by turning your head"},
            {"It is prohibited to overtake on the left side", "You are allowed to overtake on the left or right side if there is no danger", "It is prohibited to overtake on the right side"},
            {"The road is two-way", "The road has two or more lanes going in one direction", "The sidewalk is wide"},
            {"30 kph", "20 kph", "35 kph"},
            {"An honor", "A privilege", "A right"},
            {"Stare at the glaring light", "Do not look at glaring light, quickly look on the right side of the road", "Switch your headlight on high also"},
            {"Immediately turn and sound your horn", "Ignore giving a signal", "Give signal not less than 30 meters before turning"},
            {"Driver’s license", "Driver’s license, vehicle registration, and receipt of last LTO payment for the vehicle", "Driver’s license and vehicle insurance paper"},
            {"No entry", "Stop", "Give way"},
            {"Three meters from the back of the car", "One meter from the back of the car", "Two meters from the back of the car"},
            {"Regulatory sign", "Warning sign", "Giving direction"},
            {"Allowing vehicles to go right or left", "Pedestrians can cross", "It is prohibited to enter on the direction of the arrow"},
            {"Slow down, stay on the right, and let it overtake", "Stay on the right and stop", "Sound your horn and let it pass"},
            {"Follow the direction painted on the road", "You are allowed to change lanes", "Slow down"},
            {"Stop at the given line", "Drive faster", "Stop for a while and continue if there is no danger"},
            {"Give way to vehicles going from left and right, proceed if there is no danger", "Stop and proceed if there is no danger", "Slow down and proceed if there is no danger"},
            {"The vehicles facing the green light", "The vehicles approaching the roundabout", "The vehicles in the roundabout"},
            {"Priority side junction on the right", "Priority merge on the right", "Priority side junction"},
            {"Your left hand pointing upward", "Your right hand pointing upward", "Your right hand pointing to the right"},
            {"Warning sign", "Information sign", "Reminder sign"},
            {"No entry for train", "Warning intersection", "Railroad crossing advance warning"},
            {"Separates traffic going in one direction", "Divides lanes going in one direction", "Sign that you can go left or right"},
            {"You can overtake on the left or right side", "It is prohibited to overtake on the left side", "It is prohibited to overtake on the right side"},
            {"17 years old", "18 years old", "16 years old"},
            {"The vehicle is stationary with the engine turned off", "The vehicle is not moving while loading passengers", "The vehicle is not moving while unloading passengers"},
            {"Turn right or left", "Depress the horn", "Prepare to push the brake"},
            {"To the sidewalk curb", "Parallel with the sidewalk curb", "Away from the sidewalk curb"},
            {"Turning left", "Changing lanes", "Turning right"},
            {"It is prohibited to overtake", "You are allowed to overtake", "All answers are correct"},
            {"If you want", "Not less than once per one minute", "Quickly"},
            {"Prepare to stop, red traffic light is about to light up", "Stop", "You can go, but slow down"},
            {"Stop and wait for the traffic light to change", "Slow down and proceed if there is no danger", "Wait for the green light"},
            {"30 meters", "15 meters", "60 meters"},
            {"Road widens", "Road narrows", "Slippery road"},
            {"Look around first", "Immediately go", "Sound your horn"},
            {"Next intersection distance is 30 km", "Width restriction", "Given speed limit"},
            {"Stop and proceed if there is no danger ahead", "Slow down and proceed if there is no danger ahead", "Wait for the green signal"},
            {"30 days", "10 days", "15 days"},
            {"Dangerous curve to the right", "Dangerous curve to the left", "Dangerous bend"},
            {"Bumpy road", "Slippery road", "Steep road"},
            {"No entry for bus", "No entry for car", "No entry for jeepney"},
            {"Pull over to the right and slow down or even stop if necessary", "Speed up so that you don’t hold the ambulance", "Stop as soon as possible"},
            {"Animal cage", "Animal crossing", "Animals are prohibited to cross"},
            {"If there is a heavy traffic", "If he is a good driver", "While driving to anticipate other driver’s actions"},
            {"Ten seconds before doing it", "Five minutes before doing it", "One minute before doing it"},
            {"No parking", "Do not blow your horn", "No entry"},
            {"Beware of falling rocks", "Road under construction", "Steep road"},
            {"Apply for a duplicate license", "File an affidavit of loss and apply for a duplicate license", "Apply for a new license"},
            {"Steep road", "Road under construction", "Quayside or river bank"},
            {"The vehicle should not stop", "The vehicle should slow down", "The vehicle should stop"},
            {"In a pedestrian crossing", "In a certain place you want to go", "In a given parking space"},
            {"Speed is in accordance with the given speed limit", "There is no danger in the road", "All answers are correct"},
            {"It is prohibited to overtake on the left side", "You are allowed to overtake on left or right side if there is no danger", "It is prohibited to overtake on the right side"},
            {"Stop every once in a while and rest", "Drink alcohol before driving", "Drink medicine that prevents sleepiness"},
            {"Proves that you are a good driver", "Saves fuel", "May engage you in an accident"},
            {"Steep descent", "Steep road", "Steep ascent"},
            {"The last one to arrive", "The first one to slow down", "The first one to arrive"},
            {"Condition of the vehicle", "Road and weather conditions", "Capability of the driver"},
            {"Php 1,500.00 and six months suspension in obtaining a license", "Not more than six months imprisonment", "Php 300.00"},
            {"Do not enter", "Do not enter if the vehicle is more than 2 meters wide", "Do not enter if the vehicle is 2 meters wide"},
            {"21 years old", "18 years old", "17 years old"},
            {"No entry", "No left turn", "One-way traffic"},
            {"Stopping", "Turning right", "Turning left"},
            {"Php 1000.00", "Php 1500.00", "Php 1500 and the vehicle will be impounded up to 10 days"},
            {"Slow down", "Abruptly push the brake", "Speed up"},
            {"Turn left", "Turn right", "Stop"},
            {"Watch out for oncoming vehicles", "Sound your horn", "Turn on the vehicle’s headlight"},
            {"All answers are correct", "Plan your route and make sure the vehicle is running in good condition", "Prepare the necessary tools that can be used to repair the vehicle"},
            {"Public utility vehicles", "Private vehicles", "All types of vehicles"},
            {"The same length as a full vehicle", "The same length as two full vehicles", "The same length as three full vehicles"},
            {"Road under construction", "Bumpy road", "Slippery road"},
            {"Priority crossroads", "First aid station", "Railroad crossing"},
            {"Middle lane", "Right lane", "Left lane"},
            {"Stop at the given line", "Go signal for the vehicle", "You are allowed to proceed by slowing down"},
            {"Steep road", "Slippery road", "Bumpy road"},
            {"Warning sign", "Giving direction", "Information sign"},
            {"No entry for car", "No entry for power-driven vehicles drawing a trailer", "No entry for bus"},
            {"Railroad crossing advance warning", "School zone/Children crossing", "Hospital zone"}
    };

    private String mCorrectAnswers [] = {
            "All answers are correct", "Sharp turn to the left", "All answers are correct",
            "Double turn to the left", "Immediately", "No blowing of horns",
            "Giving warning to avoid accident", "The red arrow traffic light is about to light up", "You have to be aware and cautious from vehicles coming from left or right sides of the road",
            "You are allowed to overtake on the left side", "Right lane", "Broken yellow line",
            "It is dangerous to overtake", "No entry for trucks", "Vehicles allowed indicated in your license",
            "You cannot see oncoming vehicles", "He/she is paid or earns money while driving a private or public vehicle", "Give way",
            "Don’t force your rights", "Use the rear view mirror to check the vehicle you have overtaken", "You are allowed to overtake on the left or right side if there is no danger",
            "The road has two or more lanes going in one direction", "20 kph", "A privilege",
            "Do not look at glaring light, quickly look on the right side of the road", "Give signal not less than 30 meters before turning", "Driver’s license, vehicle registration, and receipt of last LTO payment for the vehicle",
            "Stop", "One meter from the back of the car", "Regulatory sign",
            "Allowing vehicles to go right or left", "Slow down, stay on the right, and let it overtake", "Follow the direction painted on the road",
            "Stop for a while and continue if there is no danger", "Stop and proceed if there is no danger", "The vehicles in the roundabout",
            "Priority merge on the right", "Your left hand pointing upward", "Warning sign",
            "Railroad crossing advance warning", "Separates traffic going in one direction", "It is prohibited to overtake on the left side",
            "18 years old", "The vehicle is stationary with the engine turned off", "Prepare to push the brake",
            "Away from the sidewalk curb", "Turning left", "It is prohibited to overtake",
            "Quickly", "Prepare to stop, red traffic light is about to light up", "Slow down and proceed if there is no danger",
            "30 meters", "Road narrows", "Look around first",
            "Given speed limit", "Stop and proceed if there is no danger ahead", "15 days",
            "Dangerous bend", "Slippery road", "No entry for jeepney",
            "Pull over to the right and slow down or even stop if necessary", "Animal crossing", "While driving to anticipate other driver’s actions",
            "Ten seconds before doing it", "No parking", "Beware of falling rocks",
            "File an affidavit of loss and apply for a duplicate license", "Quayside or river bank", "The vehicle should not stop",
            "In a pedestrian crossing", "All answers are correct", "You are allowed to overtake on left or right side if there is no danger",
            "Stop every once in a while and rest", "May engage you in an accident", "Steep ascent",
            "The last one to arrive", "Road and weather conditions", "Php 1,500.00 and six months suspension in obtaining a license",
            "Do not enter if the vehicle is more than 2 meters wide", "18 years old", "No entry",
            "Stopping", "Php 1500.00", "Slow down",
            "Turn right", "Watch out for oncoming vehicles", "All answers are correct",
            "Private vehicles", "The same length as a full vehicle", "Road under construction",
            "Priority crossroads", "Right lane", "Go signal for the vehicle",
            "Bumpy road", "Information sign", "No entry for power-driven vehicles drawing a trailer",
            "School zone/Children crossing"
    };

    public String getQuestion(int a) {
        return mQuestions[a];
    }

    public String getChoice1(int a) {
        return  mChoices[a][0];
    }

    public String getChoice2(int a) {
        return  mChoices[a][1];
    }

    public String getChoice3(int a) {
        return  mChoices[a][2];
    }

    public String getCorrectAnswer(int a) {
        return mCorrectAnswers[a];
    }
}
